<script lang="ts" setup>

</script>

<template>
    <div>sadasd</div>
    <div>sadasd</div>
    <div>sadasd</div>
    <div>sadasd</div>
    <div>sadasd</div>
    <div>sadasd</div>
    <div>sadasd</div>
    <div>sadasd</div>
    <div>sadasd</div>
    <div>sadasd</div>
    <div>sadasd</div>
    <div>sadasd</div>
    <div>sadasd</div>
    <div>sadasd</div>
    <div>sadasd</div>
    <div>sadasd</div>
    <div>sadasd</div>
    <div>sadasd</div>
    <div>sadasd</div>
    <div>sadasd</div>
    <div>sadasd</div>
    <div>sadasd</div>
        <div>sadasd</div>
    <div>sadasd</div>
    <div>sadasd</div>
    <div>sadasd</div>
    <div>sadasd</div>
    <div>sadasd</div>
    <div>sadasd</div>
    <div>sadasd</div>
    <div>sadasd</div>
    <div>sadasd</div>
    <div>sadasd</div>
    <div>sadasd</div>
    <div>sadasd</div>
    <div>sadasd</div>
    <div>sadasd</div>
    <div>sadasd</div>
    <div>sadasd</div>
    <div>sadasd</div>
    <div>sadasd</div>
    <div>sadasd</div>
    <div>sadasd</div>
    <div>sadasd</div>
    <div>sadasd</div>
    <div>sadasd</div>
    <div>sadasd</div>
    <div>sadasd</div>
    <div>sadasd</div>
    <div>sadasd</div>
    <div>sadasd</div>
    <div>sadasd</div>
    <div>sadasd</div>
</template>
<script lang="ts" setup>
definePageMeta({
  layout: 'dashboard'
})
</script>
